### ISSUE TITLE
Duda acerca de definición de la cobertura GICC

### ISSUE THREAD

**Issue by bjassael** [IIC3745-2019-2/syllabus#12]
Hola!
Tengo dos preguntas dirigidas a la definición de GICC que se encuentra en la slide 7 en el pdf clase 8.
Bajo la definición:
"Por cada p ∈ P y cada **cláusula mayor** ci ∈ Cp, escoja las cláusulas menores cj con i ≠ j de modo que ci no determina p."
Si se escoge las cláusulas cj de modo que ci no determina p, por definición ci deja de ser mayor. En la práctica hay que encontrar los cj de tal manera que que ci deje de ser mayor. El sentido de hacerlo sobre cada cláusula mayor ci (y no simplemente todas las cláusulas) es que si esta no puede ser mayor, ¿es una cláusula innecesaria y no vale la pena probar los valores de esta cláusula? ¿Por eso se hace sobre las cláusulas mayores y no todas las cláusulas del predicado?
La otra pregunta va dirigida a los TR. Hay casos donde no es posible generar todos los casos de prueba en la definición: 
"TR contiene cuatro requisitos por cada ci:
1. ci se evalúa como verdadero con p verdadero
2. ci se evalúa como falso con p verdadero
3. ci se evalúa como verdadero con p falso
4. ci se evalúa como falso con p falso"

Por Ej: 
Para el predicado "p = (a & b)" tomamos la cláusula "a" como mayor. Para que deje de ser mayor tomamos b = false. 
Para definir los **tr** tomamos a = true -> p = false, a = false -> p = false.
Ahora si tomamos b = true, "a" pasa a ser activa. No es posible hacer que "p" tome el valor **true** siendo "a" inactiva. Por tanto no es posible cumplir todos los **tr**. ¿Se consideran como casos infactibles? Si esto es así, la respuesta para cumplir esta cobertura sería (T F), (F F), (F T).

Gracias

**Comment by rasaffie** [comment]
Hola Benjamín,

> "[...] ¿es una cláusula innecesaria y no vale la pena probar los valores de esta cláusula? ¿Por eso se hace sobre las cláusulas mayores y no todas las cláusulas del predicado?"

Así es: solamente se validan estos requisitos sobre las cláusulas que de alguna forma son mayores en el predicado. Esto también es una forma de decir que se evalúan las cláusulas que son relevantes en el predicado (y las que no lo son se podrían eliminar).

> "Ahora si tomamos b = true, "a" pasa a ser activa."

Este criterio de cobertura no exige que las cláusulas sean activas paras todos los requisitos de prueba que surgen de cada cláusula mayor. De hecho, exigir que la cláusula _a_ no determine el valor del predicado es lo mismo que decir que _a_ no sea activa. Por otra parte, en los criterios de cobertura pueden surgir requisitos de prueba infactibles (como el 2º de tu ejemplo: `a = false` y `p = true`). Los requisitos infactibles no se incluyen al momento de considerar la cobertura total de los requisitos.

**Comment by bjassael** [comment]
Gracias profesor, me quedo clara la explicación.
