### ISSUE TITLE
Duda Test de modelo Usuarios con Devise

### ISSUE THREAD

**Issue by isipalma** [IIC3745-2019-2/syllabus#14]
Hola!

En mi grupo utilizamos la gema Devise, por lo cual me surge esta duda:

Dado que el modelo de usuarios es manejado por la gema Devise. ¿Debe probarse con test de modelos dado que es manejado por devise? Recuerdo que el profesor menciono algo sobre que no lo testearamos, pero noe stoy segura.

Saludos y gracias de antemano!

**Comment by rasaffie** [comment]
Hola Isidora,

En clases dije que las funcionalidades que agregan las librerías no se debe probar (al igual que el _framework_ o lenguaje de programación que se esté utilizando) ya que se espera que estas herramientas ya hayan sido probadas por sus desarrolladores.

En el caso de _devise_ dije que no se deben probar sus controladores y vistas ya que son autogenerados y están ocultos. En las aplicaciones que utilizan _devise_ no se crean estos archivos a menos que se quiera modificar la lógica por defecto, por lo que si uno no interviene en estos no es necesario probarlos. 

Sin embargo, el caso del modelo de usuarios es distinto, ya que sí se genera un archivo que además de las funcionalidades de _devise_ debería tener comportamiento adicional propio a la lógica de negocio de sus aplicaciones, el cual sí debería ser probado por ustedes.

En resumen, no es necesario que prueben las funcionalidades mismas de _devise_ pero sí como sus aplicaciones interactúan con esta librería.
