### ISSUE TITLE
2 versiones de postgresql distintas

### ISSUE THREAD

**Issue by miguelramirezv** [IIC3745-2019-2/syllabus#15]
Hola! Al correr el comando Docker-compose up, me sale el siguiente problema:

db_1   | 2019-10-23 00:39:19.961 UTC [1] LOG:  starting PostgreSQL 12.0 (Debian 12.0-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
db_1   | 2019-10-23 00:39:19.961 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1   | 2019-10-23 00:39:19.962 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1   | 2019-10-23 00:39:19.969 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1   | 2019-10-23 00:39:20.083 UTC [22] LOG:  database system was shut down at 2019-10-23 00:39:08 UTC
db_1   | 2019-10-23 00:39:20.118 UTC [1] LOG:  database system is ready to accept connections

Me pasó cuando actualicé a la última versión de Docker hace 4 días y sigo con el mismo problema aunque reinstalé Docker y Postgresql. 

Alguna idea de que podria ser? en stackoverflow lo unico que encontre fue este [ link ](https://stackoverflow.com/questions/44221938/postgres-container-crashes-with-database-files-are-incompatible-with-server-af) de volver a un contenedor previo o algo asi (a mi no me sirvio pero tal vez a alguien mas le sirva 🤷‍♂️)

**Comment by rasaffie** [comment]
¿A qué te refieres con reinstalar postgresql? ¿En tu máquina estás ejecutando postgres y docker en paralelo?

Por otra parte, para limpiar los _containers_, _images_, _networks_ y _volumes_ que no estés usando debes ejecutar `docker system prune --volumes`. Con `docker-compose ps` puedes ver los servicios que están activos y `docker-compose down` puedes detenerlos.

Por último, revisando el repositorio de su grupo me parecen extrañas las configuraciones que utilizan. Te recomiendo que las compares con [el respositorio de ejemplo](https://github.com/IIC3745-2019-2/ejemplo-configuracion) para ver si alguna diferencia es la causa del error.

**Comment by miguelramirezv** [comment]
Gracias profesor!  Raramente se me solucionó solo el problema (de un día a otro empezó a correr bien)
