### ISSUE TITLE
Fechas del curso

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC3745-2019-2/syllabus#17]
Estimados ayudantes y profesor: escribo para consultar si existe alguna información acerca de las nuevas fechas del curso, a fin de poder reducir la incertidumbre e ir priorizando las distintas cosas de la universidad.
Muchas gracias
Saludos cordiales

**Comment by rasaffie** [comment]
Acabo de enviar un anuncio aclarando estos puntos.

Saludos.
