### ISSUE TITLE
Se puede usar React ?

### ISSUE THREAD

**Issue by ifcarrera** [IIC3745-2019-2/syllabus#4]
Hola!
¿Para el proyecto se espera que lo hagamos completo en RoR o podemos usarlo solo como _backend_ y hacer el _frontend_ en algo más?

Salu2

**Comment by gantunesr** [comment]
Queda al criterio de cada grupo, la idea es que solo usen RoR para no aumentar el número de herramientas y dependencias. Recuerda que el foco principal del proyecto es testing, por lo que, en el caso de usar React, deben presentar el testing apropiado en relación a la herramienta, y esto se puede volver complejo en el poco tiempo que hay para el proyecto.

Recomiendo que investiguen como harán el testing y el tiempo que necesitarán en desarrollar el proyecto (si es necesario, validar con el profesor o algún ayudante todas las herramientas que van a usar para el desarrollo y testing), y proceder a partir de eso.
