### ISSUE TITLE
Mockups para la entrega 1

### ISSUE THREAD

**Issue by josemlira** [IIC3745-2019-2/syllabus#5]
Hola!

En la primera entrega se nos pide realizar _mockups_ de las diferentes vistas. Solo para estar seguro, esperan que entreguemos _mockups_ o con _wireframes_ es suficiente?

Saludos 😄

**Comment by gantunesr** [comment]
Lo importante es poder ver todas las funcionalidades definidas en las vistas, se espera cierto nivel de calidad, pero no se exige que este hecho con alguna herramienta en particular.
