### ISSUE TITLE
Permisos repositorio y Travis CI

### ISSUE THREAD

**Issue by fnmendez** [IIC3745-2019-2/syllabus#6]
Hola,

No estoy seguro si tenemos los permisos suficientes o si no encuentro cómo hacer funcionar Travis CI con el repositorio.

Gracias de antemano.

- **En Travis CI**

  ![image](https://user-images.githubusercontent.com/20799436/64153239-73d06280-cdfc-11e9-89e3-9357eebe3f99.png)

- **En GitHub**
  ![image](https://user-images.githubusercontent.com/20799436/64153283-8b0f5000-cdfc-11e9-9c61-6ab55b887b89.png)

@stephichau

**Comment by stephichau** [comment]
Hola @fnmendez ! Tienes que asegurarte que tienes la cuenta de estudiante validada y de ahi configurar travis CI; En caso de que no sea así, veremos otra solución :).

**Comment by fnmendez** [comment]
Ingresé con GitHub, supongo que ese badge quiere decir que tengo cuenta de estudiante.

![image](https://user-images.githubusercontent.com/20799436/64268160-969a6e00-cf05-11e9-83eb-6b5b8c36a1cb.png)

**Comment by fnmendez** [comment]
Tampoco puedo proteger las ramas del repositorio.

¿Cómo aplicamos esas buenas prácticas?

**Comment by rasaffie** [comment]
Hola Franco,

Me contacté con la gente de Travis y me confirmaron que la cuenta de estudiantes solamente funciona para repositorios privados a nombre de cada estudiante, no dentro de una organización.

Estoy realizando las gestiones necesarias para que habiliten nuestra organización con un plan educacional gratuito. Apenas nos aprueben la solicitud se los notificaré para que puedan integrar Travis a sus proyectos.

A pesar de esto para la primera entrega se les pedirá que hayan agregado el archivo de configuración de Travis, aunque no funcione la integración por el momento.

Por otra parte, no les habilitaremos permisos de administrador sobre sus repositorios porque estos les entregan mayores facultades de las que queremos compartir con ustedes (como por ejemplo agregar colaboradores al repositorio). Si quieren proteger sus _branches_ principales (a pesar de que esto no era una exigencia del proyecto) les pido que contacten a su ayudante para que este lo haga por ustedes.

Saludos,

**Comment by rasaffie** [comment]
Ahora está habilitado el plan educacional de Travis en la organización para que los utilicen en sus repositorios.

**Comment by roy350** [comment]
Gracias profe 🙌🏻

**Comment by NachoCasta** [comment]
Hola!

Intentando agregar el repositorio a Travis CI, no logro encontrarlo.

![image](https://user-images.githubusercontent.com/20785374/64484613-2cc2e280-d1eb-11e9-916e-a528affc70db.png)

Me aparece que Travis CI no tiene acceso a la organización.

![image](https://user-images.githubusercontent.com/20785374/64484616-42d0a300-d1eb-11e9-8b8a-8b6a39abf29d.png)

Se agradece la ayuda!

**Comment by NachoCasta** [comment]
Hola!

Intentando conectar el repositorio a heroku, me dice que necesito permisos de admin para poder conectarlo. Que podemos hacer?

Gracias!
