### ISSUE TITLE
Duda con uso de travis

### ISSUE THREAD

**Issue by roy350** [IIC3745-2019-2/syllabus#7]
Hola! resulta que tenia configurado travis, pero llego a 100 builds y ya no buildea mas, el tema es que si tengo la version estudiante entonces, no entiendo a que se debe, quizas hice algo mal o me falto alguna configuración. Si alguno sabe algo, me serviria mucho

![image](https://user-images.githubusercontent.com/20785160/64193568-05ff5780-ce4b-11e9-9b64-9f302c260ab5.png)

![image](https://user-images.githubusercontent.com/20785160/64193595-16173700-ce4b-11e9-91ea-f7bee67a41c6.png)

**Comment by rasaffie** [comment]
Ver https://github.com/IIC3745-2019-2/syllabus/issues/6

**Comment by rasaffie** [comment]
Ver https://github.com/IIC3745-2019-2/syllabus/issues/6 nuevamente.
