### ISSUE TITLE
Coverage de Views con SimpleCov

### ISSUE THREAD

**Issue by LuisFros** [IIC3745-2019-2/syllabus#8]
Despues de investigar no he logrado encontrar como hacer coverage de las vistas en Rails. 
Encontre estas preguntas: 
- [How do i get coverage for views in rails](https://stackoverflow.com/questions/21451540/how-do-i-get-coverage-for-views-in-rails)
- [Why-isnt-simplecov-checking-any-of-my-rails-views](https://stackoverflow.com/questions/37136643/why-isnt-simplecov-checking-any-of-my-rails-views)

Ademas, en una [issue](https://github.com/colszowka/simplecov/issues/745) de *SimpleCov*, dicen que efectivamente no se puede hacer coverage de las vistas.
Es mas, es un feature propuesto en esta [issue](https://github.com/colszowka/simplecov/issues/345)

El problema principal viene de que las vistas no son **.rb**

**Comment by LuisFros** [comment]
Que herramientas debemos usar para medir el Coverage de los Views?

**Comment by rasaffie** [comment]
Como bien dices, no hay una herramienta empaquetada para registrar el _coverage_ de las vistas. Por esta razón no se les controlará 100% de _coverage_ de vistas, pero sí se revisará que implementen las pruebas principales sobre estas.

De todas formas, si se respetan las buenas prácticas de un modelo _MVC_ en que se evita poner lógica de negocio en las vistas, se puede tener un buen nivel de confianza sobre las vistas si es que se prueban todos los casos de los _controllers_ y _helpers_ de la aplicación.

También, para tener más confianza sobre estas se puede configurar que la herramienta para realizar _tests_ haga efectivamente _render_ del _html_, pero esto genera que los _tests_ tarden más tiempo en ejecutarse. Por ejemplo, esto es [una funcionalidad opcional para RSpec que se debe habilitar](https://relishapp.com/rspec/rspec-rails/v/2-5/docs/controller-specs/render-views#render-views-globally). Sin embargo, esto solamente prueba que las vistas no tengan problemas al construirse, por lo que no se garantiza que visualicen lo que uno espera.

Por último, generalmente los errores de vistas se detectan más fácilmente que los errores de _back-end_, ya que los usuarios notifican rápidamente si es que el _front-end_ falla. Por esta razón se suele asegurar que los elementos principales del _front-end_ estén presentes.

**Comment by LuisFros** [comment]
Perfecto. Me quedo muy claro
Muchas gracias!!
