### ISSUE TITLE
Deploy automático a heroku con Travis CI

### ISSUE THREAD

**Issue by srvasquez** [IIC3745-2019-2/syllabus#9]
Hola estaba intentando hacer el deploy automático con travis a heroku y me encontré con el siguiente problema de permisos, de ante mano gracias.
![imagen](https://user-images.githubusercontent.com/17626486/65732903-64160800-e0a2-11e9-91ee-c0a0876f36a4.png)

**Comment by entamburini** [comment]
Creo que deberías ver el #6
